### ISSUE TITLE
Scan fails after removing old button and scanning again

### ISSUE THREAD

**Issue by DennisBlock** [50ButtonsEach/flic2lib-android#23]
If we remove the pairing of a device and immediately after scan for a new button, the scan fails. This also happens in the sample app.

Steps to reproduce:
1. Scan and connect to a button.
2. Remove the button
3. Click on scan again. Scan fails immediately with RESULT_FAILED_BUTTON_ALREADY_CONNECTED_TO_DEVICE. This happens a few times when you click on scan. Sometimes after the errors the button is connected without even pressing and holding the button.

How should we deal with it or can you fix this.

**Comment by Emill** [comment]
If you wait some seconds between 2. and 3., does the issue go away? If so, how many seconds?

**Comment by DennisBlock** [comment]
Just did some rough tests with the sample app. If I wait about 3s-4s the the scan does not show the result failed error, but the button is immediately connected again. After about 25s I can normally scan again with pressing and holding the button. 

If I click the scan button repeatedly after the errors, I often get a normal scan faster.

**Comment by Emill** [comment]
There are several reasons for the behaviours you see:

1. Android has a timer to wait a few seconds to actually disconnect the BLE link after instructed to disconnect by the app. During this time, even if asking the system if the device is connected or not, it says "disconnected", which I would say is a bug. We ask the system in https://github.com/50ButtonsEach/flic2lib-android/blob/master/flic2lib-android/src/main/java/io/flic/flic2libandroid/Flic2Manager.java#L352 to determine if it is this phone the button is connected to, and only deliver the "connected to other device" error message if that's not the case. Unfortunately due to this bug it looks like the button is connected to another device, and there is not much we can do about that.

2. When the button has been held for a few seconds, it is set to "public mode", as explained in https://github.com/50ButtonsEach/flic2-documentation/wiki/Technical-Overview-and-Terminology#switching-between-modes. If you pair and unpair within 30 seconds, the button still has a few seconds it will remain in public mode. If you then start scanning during the button is in public mode, it will attempt to pair to this button.

So, the situation you describe is not much we can do about, but fortunately we see it unlikely it will affect any end user.

**Comment by DennisBlock** [comment]
Alright, got it. Thanks!
