### ISSUE TITLE
Could not read data from flic2 device

### ISSUE THREAD

**Issue by khushalt10** [50ButtonsEach/flic2lib-android#25]
Hi,

We are trying to communicate with Flic2 BLE device on android using [react-native-ble-manager](https://github.com/innoveit/react-native-ble-manager), we were able to connect to the device and retrieve following characteristics 

`[{"characteristic": "2a00", "properties": {"Read": "Read"}, "service": "1800"}, {"characteristic": "2a01", "properties": {"Read": "Read"}, "service": "1800"}, {"characteristic": "2a05", "descriptors": [[Object]], "properties": {"Indicate": "Indicate"}, "service": "1801"}, {"characteristic": "00420001-8f59-4420-870d-84f3b617e493", "properties": {"WriteWithoutResponse": "WriteWithoutResponse"}, "service": "00420000-8f59-4420-870d-84f3b617e493"}, {"characteristic": "00420002-8f59-4420-870d-84f3b617e493", "descriptors": [[Object]], "properties": {"Notify": "Notify"}, "service": "00420000-8f59-4420-870d-84f3b617e493"}]`

We have tried both `read` and `startNotification` methods and also managed to get the response `[101]` , but on device click the `BleManagerDidUpdateValueForCharacteristic` is not receiving any data

We were able to read the actions for itag BLE device, but not able to same with flic2. please let us know if this is an issue regarding your device or the package.

Thanks

**Comment by jdegger** [comment]
You might wanna try our unofficial flic2 lib for react-native: https://github.com/X-Guard/react-native-flic2

**Comment by Emill** [comment]
In order to make the user experience more secure and robust, we have designed a protocol that must be used when communicating with the button, documented here: https://github.com/50ButtonsEach/flic2-documentation/wiki/Flic-2-Protocol-Specification. So it's not as simple as just turning on notifications.

The flic2lib-android library implements this protocol for you. The link that jdegger provided is a react-native wrapper for our library that you can try out.
