### ISSUE TITLE
Button callback listener

### ISSUE THREAD

**Issue by wesdewitte** [50ButtonsEach/flic2lib-android#6]
I've got everything working right now, with the service running in the background. But when the application restarts the listener of the button isn't correct anymore it points to the old application. So i have to remove the listener in the onDestroy and add again in de oncreate??, but i want to listen to it in the background when the application isn't running i'm making it so that i can start the application again. That works, i can restart our app but because of the restart the listener is not correct anymore so i don't get the event in our app.   

The main goal is to add a listener once. And then it should always response either to the app or restart the app and then receiving the event in the app.

Any idea how to solve this?

**Comment by Emill** [comment]
What do you mean? The https://developer.android.com/reference/android/app/Application class does not have any `onDestroy` method.

**Comment by wesdewitte** [comment]
Oh yeah sorry had to mention that we are porting it to react native. So in react native we do have onDestroy.  Progress can be found here: https://github.com/X-Guard/react-native-flic2/tree/feature/add_service

**Comment by wesdewitte** [comment]
Oh yeah sorry had to mention that we are porting it to react native. So in react native we do have onDestroy.  Progress can be found here: https://github.com/X-Guard/react-native-flic2/tree/feature/add_service

**Comment by Emill** [comment]
And when does onDestroy get called then?

**Comment by Emill** [comment]
To be a bit more detailed, the Application class (https://developer.android.com/reference/android/app/Application) is created only once during the app process's lifetime. The https://github.com/50ButtonsEach/flic2lib-android-sample sample project uses the Application class for initiating the flic2lib and registering a callback. The Application class is never destroyed.

All other Android components have a "lifecycle". For example Activity lifecycle is described in https://developer.android.com/guide/components/activities/activity-lifecycle. The same for Services. This means a service or activity can be created and destroyed many times while the Application is alive. If you want for example a Flic click listener to be active while an activity is in the foreground, you should register it in onResume and unregister it in onPause.

Since flic2lib is a singleton, it will be alive until the application process terminates. So if you want a listener to be active the whole time, even when no Services or Activities are running, you should register the listener only once, for example in your Application class's onCreate method.

> "but i want to listen to it in the background when the application isn't running i'm making it so that i can start the application again."

It doesn't really work this way, since the application must run (the process must be alive) in order to be Bluetooth connected and have the possibility to get button events. For that to happen you generally must have a Foreground Service running so that the system doesn't kill the process.

I'm not familiar with React Native so I don't know right now how the Android components are mapped there.

**Comment by wesdewitte** [comment]
Oke i understand what you are saying. So in the application i should initialize the manager and listener to know buttons. And then in our ported lib i should call Flic2manager.getInstance to retrieve the manager from the android application. In this way every time i call getInstance i get the manager that is set in the application is that correct?

**Comment by Emill** [comment]
Yes!
